name: 'Deploy Greetings app'
description: 'Action to deploy Greetings app'
inputs:
  environment:
    description: 'Environment where to deploy application'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "Deployment triggered on ${{ inputs.environment }} environment.."
      shell: bash
    - name: Stop previous container
      run: docker-compose stop greetings-app-${{ inputs.environment }}
      shell: bash
    - name: Remove stopped container
      run: docker-compose rm greetings-app-${{ inputs.environment }}
      shell: bash
    - name: Run new container
      run: docker-compose up -d greetings-app-${{ inputs.environment }}
      shell: bash